specVersion: 0.2.0
name: networkfilterexample
version: 1.0.0
description: Network Filter
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws

definitions:
  mapping: &globalDefinitions
    file: ./dist/index.js
    handlers:
      - handler: handleBlock
        kind: substrate/BlockHandler
      - handler: handleEvent
        kind: substrate/EventHandler
        filter:
          module: balances
          method: Deposit 
      - handler: handleCall
        kind: substrate/CallHandler

dataSources:
  - name: polkadotEndpoint
    kind: substrate/Runtime
    filter:
      specName: polkadot
    startBlock: 1000
    mapping: *globalDefinitions
  - name: kusamaEndpoint
    kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 15000
    mapping: *globalDefinitions
    
